global:
  namespace: default
  ingress:
    enabled: false  
    host: example.com

database:
  enabled: true
  name: mydatabase
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  initScripts:
    enabled: true

primary:
  persistence:
    enabled: true
    size: 1Gi

services:
  gateway:
    type: NodePort
    enabled: false
    replicaCount: 2
    image:
      repository: milica764/gateway
      tag: latest
    ports:
      - name: http
        containerPort: 8080
        servicePort: 80 
    env:
      - name: SERVICE_NAME
        value: gateway

  reservation:
    enabled: false
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/reservation
      tag: latest
    ports:
      - name: http
        containerPort: 8070
        servicePort: 8070
    env:
      - name: SERVICE_NAME
        value: reservation
    database:
      host: postgres-postgresql
      port: 5432
      name: reservations
      user: postgres
      password: postgres

  payment:
    enabled: false
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/payment
      tag: latest
    ports:
      - name: http
        containerPort: 8060
        servicePort: 8060
    env:
      - name: SERVICE_NAME
        value: payment

    database:
      host: postgres-postgresql
      port: 5432
      name: payments
      user: postgres
      password: postgres

  loyalty:
    enabled: false
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/loyalty
      tag: latest
    ports:
      - name: http
        containerPort: 8050
        servicePort: 8050
    env:
      - name: SERVICE_NAME
        value: loyalty

    database:
      host: postgres-postgresql
      port: 5432
      name: loyalties
      user: postgres
      password: postgres
