global:
  namespace: default
  ingress:
    enabled: false  
    host: example.com

database:
  enabled: true
  name: mydatabase
  user: postgres
  password: postgres
  host: postgres-postgresql
  port: 5432
  initScripts:
    enabled: true

primary:
  persistence:
    enabled: true
    size: 1Gi

services:
  postgres:
    enabled: true
    replicaCount: 1
    image:
      repository: milica764/my-postgres
      tag: latest
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_DB
        values: "mydatabase"

    type: ClusterIP
    port: 5432

  gateway:
    type: NodePort
    enabled: false
    replicaCount: 2
    image:
      repository: milica764/gateway
      tag: latest
    ports:
      - name: http
        containerPort: 8080
        servicePort: 80 
    env:
      - name: SERVICE_NAME
        value: gateway

  reservation:
    enabled: false
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/reservation
      tag: latest
    ports:
      - name: http
        containerPort: 8070
        servicePort: 8070
    env:
      - name: SERVICE_NAME
        value: reservation
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://postgres-postgresql:5432/reservations"
      - name: SPRING_DATASOURCE_USERNAME
        value: "postgres"
      - name: SPRING_DATASOURCE_PASSWORD
        value: "postgres"

  payment:
    enabled: false
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/payment
      tag: latest
    ports:
      - name: http
        containerPort: 8060
        servicePort: 8060
    env:
      - name: SERVICE_NAME
        value: payment
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://postgres-postgresql:5432/payments"
      - name: SPRING_DATASOURCE_USERNAME
        value: "postgres"
      - name: SPRING_DATASOURCE_PASSWORD
        value: "postgres"

  loyalty:
    enabled: false
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/loyalty
      tag: latest
    ports:
      - name: http
        containerPort: 8050
        servicePort: 8050
    env:
      - name: SERVICE_NAME
        value: loyalty
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://postgres-postgresql:5432/loyalties"
      - name: SPRING_DATASOURCE_USERNAME
        value: "postgres"
      - name: SPRING_DATASOURCE_PASSWORD
        value: "postgres"
