#global:
#  image:
#    repository: my-docker-registry/my-app
#    tag: latest
#  service:
#    type: ClusterIP
#    port: 80

services:
  gateway:
    type: NodePort
    enabled: true
    replicaCount: 2
    image:
      repository: milica764/gateway
      tag: latest
    ports:
      - name: http
        containerPort: 8080
        servicePort: 80 
    env:
      - name: SERVICE_NAME
        value: gateway

  reservation:
    enabled: true
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/reservation
      tag: latest
    ports:
      - name: http
        containerPort: 8070
        servicePort: 8070
    env:
      - name: SERVICE_NAME
        value: reservation

  payment:
    enabled: true
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/payment
      tag: latest
    ports:
      - name: http
        containerPort: 8060
        servicePort: 8060
    env:
      - name: SERVICE_NAME
        value: payment

  loyalty:
    enabled: true
    replicaCount: 2
    type: ClusterIP
    image:
      repository: milica764/loyalty
      tag: latest
    ports:
      - name: http
        containerPort: 8050
        servicePort: 8050
    env:
      - name: SERVICE_NAME
        value: loyalty
