{{- range $name, $service := .Values.services }}
{{- if and $service.enabled (eq $name $.Values.serviceName) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $service.image.repository }}:{{ $service.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ (index $service.ports 0).containerPort }}

          env:
            {{- range $service.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
---
{{- end }}
{{- end }}