
{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-microservices
spec:
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          {{- range $name, $service := .Values.services }}
          {{- if $service.enabled }}
          - path: /{{ $name }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ (index $service.ports 0).servicePort }}
          {{- end }}
          {{- end }}
{{- end }}
