{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ (index $service.ports 0).servicePort }}
      targetPort: {{ (index $service.ports 0).containerPort }}
---
{{- end }}
{{- end }}
