{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace | default "default" }} 
  labels:
    app: {{ $name }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: {{ $service.type | default "ClusterIP" }}
  selector:
    app: {{ $name }}
  ports:
    {{- range $service.ports }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
    {{- end }}
---
{{- end }}
{{- end }}
